### PR TITLE
Bump plugin helpers to 8.0.1

### PR DESCRIPTION
**Pull request by jbudz**
Pending changes in kibana 7.0.0 to move development mode from bin/kibana to scripts/kibana.  See https://github.com/elastic/kibana/pull/13806 for details.

### CODE REVIEW

**Comment by w33ble** [comment]
While you're in here, `@elastic/eslint-config-kibana` is on 0.14.0 at this point, and no doubt some of the peer dependencies have been updated...

**Comment by w33ble** [comment]
@jbudz if you'd prefer, we could merge this as-is, release a v8, and worry about updating other stuff later. Just let me know your preference, I don't mean to block this PR if you're in a hurry to get it in.

**Comment by jbudz** [comment]
```
Worker information
instance: 75e2764 travisci/ci-garnet:packer-1503972846 (via amqp)
startup: 5.112266829s
oci runtime error: exec failed: container_linux.go:265: starting container process caused "could not create session key: disk quota exceeded"
```

```
[~/Projects/elastic/template-kibana-plugin]$ npm run test                                                     [bump-plugin-helpers]

> template-kibana-plugin@7.2.3 test /Users/jbudz/Projects/elastic/template-kibana-plugin
> ava sao.test.js


  11 passed
```

Needs a little more work to get  `npm run lint` working on the top level

**Comment by w33ble** [comment]
Nice work adding the resolved to the template, and thanks for sticking with this to get the linting working. 💸

**Comment by w33ble** [comment]
Backported to 7.x in e3bfb34

**Pull request merged**
